In [3]:
inputs=[1.2,2.1,3.1]
weight=[3.2,2.3,1.2]
bias=3


output=inputs[0]*weight[0]+inputs[1]*weight[1]+inputs[2]*weight[2]+bias
print(output)

15.39


In [2]:
inputs=[1,2,3]
weight=[0.2,0.8,-0.5]
bias=2


output=inputs[0]*weight[0]+inputs[1]*weight[1]+inputs[2]*weight[2]+bias
print(output)

2.3


In [1]:
inputs=[1,2,3,4]

weight=[[0.2,0.8,-0.5,0.3],
         [0.3,0.5,0.5,0.6],
         [0.4,0.9,0.7,0.1]]

bais=[2,4,6]
import numpy as np
output=np.dot(weight,inputs)+bais
print(output)

[ 3.5  9.2 10.7]


In [4]:
inputs=[[1.0,2.0,3.0,2.5],
       [2.0,5.0,-1.0,2.0],
       [-1.5,2.2,3.7,0.8]]

weight=[[0.2,0.8,-0.5,0.3],
         [0.3,0.5,0.5,0.6],
         [0.4,0.9,0.7,0.1]]

bais=[2.0,3.0,5.0]
import numpy as np
output=np.dot(inputs,np.array(weight).T)+bais
print(output)

[[3.05 7.3  9.55]
 [7.5  6.8  9.8 ]
 [1.85 5.98 9.05]]


In [5]:
inputs=[[1.0,2.0,3.0,2.5],
       [2.0,5.0,-1.0,2.0],
       [-1.5,2.2,3.7,0.8]]

weight=[[0.2,0.8,-0.5,0.3],
         [0.3,0.5,0.5,0.6],
         [0.4,0.9,0.7,0.1]]

bais=[2.0,3.0,5.0]

weight2=[[0.1,-0.14,0.5],
        [-0.2,0.12,0.33],
        [-0.44,0.73,-0.13]]

bais2=[-1.0,2.0,-0.5]

layer1_output=np.dot(inputs,np.array(weight).T)+bais
layer2_output=np.dot(layer1_output,np.array(weight2).T)+bais2
print(layer2_output)

[[ 3.058   5.4175  2.2455]
 [ 3.698   4.55   -0.11  ]
 [ 2.8728  5.3341  1.8749]]


In [6]:
np.random.seed(0)

In [10]:
X=[[1.0,2.0,3.0,2.5],
       [2.0,5.0,-1.0,2.0],
       [-1.5,2.2,3.7,0.8]]

class dense_layer:
    def __init__(self,n_inputs,n_neurons):
        self.weight=0.10*np.random.randn(n_inputs,n_neurons)
        self.biases=np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.out=np.dot(inputs,self.weight)+self.biases
        
layer1=dense_layer(4,5)
layer2=dense_layer(5,2)
layer1.forward(X)
print(layer1.out)


[[-0.35402716 -0.25986081 -0.09275251 -0.64047221 -0.19265323]
 [-0.25353471 -0.93578807  0.15906603 -0.42559505 -0.27803059]
 [-0.23614948  0.08586301  0.26218826 -1.13525351 -0.00980175]]


In [11]:
layer2.forward(layer1.out)
print(layer2.out)

[[ 0.16518081  0.03067444]
 [ 0.19057082  0.14312839]
 [ 0.19950826 -0.06945421]]
